const express = require("express");
const router = express.Router();
const AuthRoutes = require("./auth.route");
const messageRoutes = require("./message.route");
const userRoutes = require("./user.route");
const postRoutes = require("./post.route");
const commentRoutes = require("./comment.route");
const followRoutes = require("./follow.route");
const searchHistoryRoutes = require("./searchHistory.route");
const bookmarkRoutes = require("./bookmark.route");
router.use("/auth", AuthRoutes);
router.use("/message", messageRoutes);
router.use("/comment", commentRoutes);
router.use("/user", userRoutes);
router.use("/post", postRoutes);
router.use("/follow", followRoutes);
router.use("/searchHistory", searchHistoryRoutes);
router.use("/bookmark", bookmarkRoutes);
module.exports = router;
