export const router = {
    home: '/',
    search: '/search',
    explore: '/explore',
    message: '/message',
    notification: '/notification',
    profile: '/profile/:id',
    create: '/create',
    reels: '/reels',
    login: '/login',
    register: '/register',
    chatdetail: '/message/:id',
    roomcall: '/roomcall/:id',
    roomvoice: '/roomvoice/:id',
};
